lint:
  files_exist:
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - tests/default.nf.test
  files_unchanged:
    - assets/nf-core-pixelator_logo_light.png
    - .github/PULL_REQUEST_TEMPLATE.md
  multiqc_config: false
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Pixelgen Technologies AB
  description: Pipeline for analysis of Molecular Pixelation assays
  force: false
  is_nfcore: true
  name: pixelator
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - multiqc
    - igenomes
  version: 2.0.0
