repository_type: pipeline
lint:
  template_strings: false
  nextflow_config:
    manifest.homePage: false
  files_unchanged:
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
