contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #pixelator channel"
    url: https://nfcore.slack.com/channels/pixelator
    about: Discussion about the nf-core/pixelator pipeline
