name: pixelator/demux
description: Demultiplex molecular pixelation reads according to the panel file barcodes
keywords:
  - "molecular pixelator"
  - demultiplexing
  -
tools:
  - pixelator:
      description: |
        Software package to process sequencing data into Molecular Pixelation data.
      homepage: https://github.com/PixelgenTechnologies/pixelator
      documentation: https://github.com/PixelgenTechnologies/pixelator
      arxiv: null
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        FastQ file containing the molecular pixelator amplicon.
  - antibody_panel:
      type: file
      description: |
        Panel file used by the molecular pixelator kit.

output:
  - processed:
      type: file
      description: All demultiplexed FastQ files
      pattern: "*processed*.{fq,fastq}.gz"

  - failed:
      type: file
      description: FastQ file containing reads with invalid barcodes
      pattern: "*failed.{fq,fastq}.gz"

  - report_json:
      type: file
      description: JSON file with statistics for the demux stage
      pattern: "*.report.json"

  - metadata:
      type: file
      description: Command invocation metadata files for pixelator demux
      pattern: "*.meta.json"

  - log:
    type: file
    description: Pixelator log files
    pattern: "*pixelator-demux*.log"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@fbdtemme"
