name: pixelator/concatenate
description: Demultiplex molecular pixelation reads according to the panel file barcodes
keywords:
  - "molecular pixelator"
tools:
  - pixelator:
      description: |
        Software package to process sequencing data into Molecular Pixelation data.
      homepage: https://github.com/PixelgenTechnologies/pixelator
      documentation: https://github.com/PixelgenTechnologies/pixelator
      doi: 10.1101/2023.06.05.543770
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.

output:
  - merged:
      type: file
      description: FastQ file containing combined and trimmed reads
      pattern: "*merged*.{fq,fastq}.gz"

  - report_json:
      type: file
      description: JSON file with statistics for the concatenate stage
      pattern: "*.report.json"

  - metadata:
      type: file
      description: Command invocation metadata files for pixelator concatenate
      pattern: "*.meta.json"

  - log:
    type: file
    description: Pixelator log files
    pattern: "*pixelator-concatenate*.log"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@fbdtemme"
