name: pixelator/graph
description: |
  Compute graph, components and other metrics from a edge list
  produced by pixelator collapse
keywords:
  - "molecular pixelator"
tools:
  - pixelator:
      description: |
        Software package to process sequencing data into Molecular Pixelation data.
      homepage: https://github.com/PixelgenTechnologies/pixelator
      documentation: https://github.com/PixelgenTechnologies/pixelator
      arxiv: null
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.

output:
  - edgelist:
      type: file
      description: Filtered edgelist
      pattern: "*.edgelist.csv.gz"

  - raw_edgelist:
      type: file
      description: Raw (unfiltered) edgelist
      pattern: "*.raw_edgelist.csv.gz"

  - components_recovered:
      type: file
      description: CSV file with recovered components. Only available when the --multiplet-recovery flag is set.
      pattern: "*.components_recovered.json"
      optional: true

  - report_json:
      type: file
      description: JSON file with statistics for the graph stage
      pattern: "*.report.json"

  - all_results:
      type: file
      description: All output files from the pixelator graph Command
      pattern: "*"

  - log:
    type: file
    description: Pixelator log files
    pattern: "*pixelator-graph*.log"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@fbdtemme"
