name: nf-core AWS full size tests
# This workflow is triggered on published releases.
# It can be additionally triggered manually with GitHub actions workflow dispatch button.
# It runs the -profile 'test_full' on AWS batch

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-aws-full:
    name: Run AWS full tests
    if: ${{ github.repository == 'PixelgenTechnologies/nf-core-pixelator' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.NF_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NF_AWS_SECRET_ACCESS_KEY }}

      - name: Launch workflow
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile aws_test_full,docker \
            --runName full-${{ github.run_id }} \
            --testdata_root s3://pixelgen-nf-input/nf-core-pixelator-datasets
